name: Deploy to ECS

on:
  workflow_call:

jobs:
  ECS:
    runs-on: ubuntu-latest
    steps:

    - name: Configurar credenciais aws
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Obtendo arquivo de tarefa
      run: |
        aws ecs describe-task-definition --task-definition Tarefa_API_Estudos --query "taskDefinition" > temp-task-def.json
        jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy, .enableFaultInjection)' temp-task-def.json > task-def.json
    
    - name: Atualizando imagem docker no arquivo de tarefa
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-def.json
        container-name: Go-Estudos
        image: petersonwl/go_ci:${{ github.run_number }}
        environment-variables: |
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_SSLMODE=${{ secrets.DB_SSLMODE }}
          DB_PORT=${{ secrets.DB_PORT }}
          PORT=8000
    
    - name: Deploy da tarefa para o ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: Servico-go-estudos
        cluster: api-go-estudos
        wait-for-service-stability: true
