name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      DB_HOST: localhost
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: root
      DB_PORT: 5432
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-22.04']
        go_version: ['1.18', '1.17']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Build-DB
      run: docker compose build
      
    - name: Create-DB
      run: docker compose up -d

    - name: Wait for Postgres
      run: |
        sudo apt-get update && sudo apt-get install -y postgresql-client
        until pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USERNAME" -d "$DB_NAME"; do
          echo "Aguardando Postgres..."
          sleep 2
        done

    - name: Test
      run: go test -v main_test.go 
      
  
  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-22.04']
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go